Fix "implicit declaration" compiler warnings
This fixes a bunch of the following:

	main.c:112:2: warning: implicit declaration of function 'get_term' is invalid in C99 [-Wimplicit-function-declaration]
		get_term();

	lsystem.c:317:2: warning: implicit declaration of function 'raw_mode' is invalid in C99 [-Wimplicit-function-declaration]
		raw_mode(0);

The problem was that the "public void" was space-indented, instead of
tab-indented, and then the script to generate funcs.h would ignore it.

So just replace the indentation and it's fixed.